#!/usr/bin/python
# This file is provided as a conveinence to people using the Git repository.
# It is not included in source distributions, and it is created in binary
# distributions as a setuptools entry point.
from fedora_business_cards.frontend.cmdline import main
main()
